import {
  FaHome,
  FaBriefcase,
  FaUser,
  FaDAndD,
  FaRegMoneyBillAlt,
  FaChartLine,
  FaFile,
  FaTable,
  FaTv,
  FaWrench,
  FaSyncAlt,
} from "react-icons/fa";

const project_routes = {
  ko: [
    {
      name: "대시보드",
      order: 1,
      link: "/dashboard",
      icon: <FaHome />,
      sub_menu: [],
    },
    {
      name: "회원 관리",
      order: 2,
      link: "/members",
      icon: <FaUser />,
      sub_menu: [],
    },
    {
      name: "영업 관리",
      order: 3,
      link: "/business",
      icon: <FaBriefcase />,
      sub_menu: [],
    },
    {
      name: "펀딩 관리",
      order: 4,
      link: "/fundings",
      icon: <FaDAndD />,
      sub_menu: [],
    },
    {
      name: "투자 관리",
      order: 5,
      link: "/investments",
      icon: <FaChartLine />,
      sub_menu: [],
    },
    {
      name: "채권 관리",
      order: 6,
      link: "/debts",
      icon: <FaFile />,
      sub_menu: [],
    },
    {
      name: "지급 관리",
      order: 7,
      link: "/payments",
      icon: <FaRegMoneyBillAlt />,
      sub_menu: [],
    },
    {
      name: "세무 관리",
      order: 8,
      link: "/taxes",
      icon: <FaTable />,
      sub_menu: [],
    },
    {
      name: "변경내역/로그 조회",
      order: 9,
      link: "/history",
      icon: <FaSyncAlt />,
      sub_menu: [],
    },
    {
      name: "전시/게시판 관리",
      order: 10,
      link: "/exhibitions",
      icon: <FaTv />,
      sub_menu: [],
    },
    {
      name: "시스템 관리",
      order: 11,
      link: "/system",
      icon: <FaWrench />,
      sub_menu: [
        { name: "", order: 1, link: "/" },
        { name: "", order: 2, link: "/" },
      ],
    },
  ],
  en: [
    {
      name: "Dashboard",
      order: 1,
      link: "/dashboard",
      icon: <FaHome />,
      sub_menu: [],
    },
    {
      name: "Member Management",
      order: 2,
      link: "/members",
      icon: <FaUser />,
      sub_menu: [],
    },
    {
      name: "Business Management",
      order: 3,
      link: "/business",
      icon: <FaBriefcase />,
      sub_menu: [],
    },
    {
      name: "Funding Management",
      order: 4,
      link: "/fundings",
      icon: <FaDAndD />,
      sub_menu: [],
    },
    {
      name: "Investment Management",
      order: 5,
      link: "/investments",
      icon: <FaChartLine />,
      sub_menu: [],
    },
    {
      name: "Debt Management",
      order: 6,
      link: "/debts",
      icon: <FaFile />,
      sub_menu: [],
    },
    {
      name: "Payment Management",
      order: 7,
      link: "/payments",
      icon: <FaRegMoneyBillAlt />,
      sub_menu: [],
    },
    {
      name: "Tax Management",
      order: 8,
      link: "/taxes",
      icon: <FaTable />,
      sub_menu: [],
    },
    {
      name: "Change History",
      order: 9,
      link: "/history",
      icon: <FaSyncAlt />,
      sub_menu: [],
    },
    {
      name: "Exhibition Management",
      order: 10,
      link: "/exhibitions",
      icon: <FaTv />,
      sub_menu: [],
    },
    {
      name: "System Management",
      order: 11,
      link: "/system",
      icon: <FaWrench />,
      sub_menu: [
        { name: "Menu A", order: 1, link: "/" },
        { name: "Menu B", order: 2, link: "/" },
      ],
    },
  ],
};

export default project_routes;
